### ISSUE TITLE
Utilizar arquivo `data.json` com dependências listadas na propriedade `resources`

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#16]
Acho que vai ser comum projetos em que não existe a geração de um data package como output mas ainda queremos consumir data packages como fontes de dados. Um exemplo que passei por isso foi no [checks-loa-ppag](https://github.com/splor-mg/checks-loa-ppag). Nesses casos, precisamos de inserir uma propriedade _fake_ `resources` caso contrário não conseguimos usar o frictionless-py para processamento do arquivo. No meu [exemplo](https://github.com/splor-mg/checks-loa-ppag/blob/main/datapackage.yaml) ficou:

```yaml
name: checks-loa-ppag
resources:
  - name: data
    path: data
sources:
  - name: loa
    path: https://raw.githubusercontent.com/splor-mg/loa-dados-2023/main/data/datapackage.json
  - name: ppag
    path: https://raw.githubusercontent.com/splor-mg/ppag-planejamento-dados-2023/main/data/datapackage.json
```

Pra evitar esse tipo de problema acho que faz sentido mudarmos o arquivo default para [`data.json`](https://github.com/splor-mg/dpm/blob/development/src/dpm/cli.py#L14) e armazenarmos os pacotes na propriedade `resources` no lugar de `sources.`
