### ISSUE TITLE
Permitir filtro em `data.yaml` para permitir download de um subconjunto dos recursos 

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#36]
Essa funcionalidade veio ao observar que o painel-admin-obz precisa apenas do recurso `sisor-dados-2024/data/base_orcam_despesa_item_fiscal.csv` para implementar splor-mg/painel-admin-obz#6 mas teve que baixar todos os recursos do [sisor-dados-2024](https://github.com/splor-mg/painel-admin-obz/commit/5944fa910f4291230e8721187d33d0d330a1b4ee)

**Comment by fjuniorr** [comment]
Não conheço nenhuma propriedade que possa ser usado pra isso, então minha sugestão apesar de possibilidade de confusão é usar novamente `resources`. Dessa forma para o `data.yaml`

```yaml
name: spreadmart
resources: 
  - name: reprex-excel
    path: https://raw.githubusercontent.com/splor-mg/reprex/main/reprex/20230512T084359/datapackage.json
    resources: ['plaintext', 'B']
```

A gente pode fazer

```python
from frictionless import Package

dp = Package('data.yaml')

source = Package(dp.get_resource('reprex-excel').path)

for resource_name in source.resource_names:
    resource_name in dp.get_resource('reprex-excel').custom['resources']
```

É importante que uma mensagem de warning seja mostrada se algum recurso especificado como filtro no `data.yaml` não existir na fonte de dados, como por exemplo `B`.
