### ISSUE TITLE
Usar "array of tables" em data.toml

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#51]
Seguindo a [spec](https://toml.io/en/v1.0.0#array-of-tables) a gente teria:

```toml
title = "Data Dependencies"

[[packages]]
name = "sigplan"
path = "https://raw.githubusercontent.com/splor-mg/ppag-planejamento-dados-2024/main/datapackage.yaml"
resources = ["acoes_planejamento"]
token = "GITHUB_TOKEN"

[[packages]]
name = "sisor2023"
path = "https://raw.githubusercontent.com/splor-mg/sisor-dados-2023/main/datapackage.json"

[[packages]]
name = "sisor2024"
path = "https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/datapackage.json"
resources = ["acoes_planejamento"]
```

Sendo acessado com:

```python
import tomllib

with open("data.toml", "rb") as f:
    data = tomllib.load(f)

for package in data['packages']:
    print(f'{package}')
```

```
{'name': 'sigplan', 'path': 'https://raw.githubusercontent.com/splor-mg/ppag-planejamento-dados-2024/main/datapackage.yaml', 'resources': ['acoes_planejamento'], 'token': 'GITHUB_TOKEN'}
{'name': 'sisor2023', 'path': 'https://raw.githubusercontent.com/splor-mg/sisor-dados-2023/main/datapackage.json'}
{'name': 'sisor2024', 'path': 'https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/datapackage.json', 'resources': ['acoes_planejamento']}
```

ps. Essa funcionalidade não aparece no [site principal](https://toml.io/en/).
