### ISSUE TITLE
Adicionar suporte para instalação de sources que são data packages locais

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#8]
A propriedade `sources.path` também pode ser especificada com um caminho que aponte para um data package local, usando caminho absoluto ou relativo. Exemplos: 

```yaml
name: roperacional
resources:
  - name: despesa
    path: data/despesa.csv
  - name: receita
    path: data/receita.csv
sources:
  - name: reest
    path: https://raw.githubusercontent.com/splor-mg/reestimativa-dados/dev/datapackage.yaml
  - name: loa
    path: sources/loa/datapackage.yaml # data package local com caminho relativo
  - name: ldo
    path: /home/fjuniorr/ldo/datapackage.yaml # data package local com caminho absoluto
```

Usualmente as fontes de dados especificadas como data packages locais terão recursos armazenados remotamente (ie. `resource.path` é uma URL).
